FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:3.22
WORKDIR /app
COPY --from=builder /app/server ./server
COPY .env.production ./.env.production
ENV APP_ENV=production
EXPOSE 8080
CMD ["./server"]
