// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"backend/models"
)

type AuthPayload struct {
	Token     string       `json:"token"`
	ExpiresAt string       `json:"expiresAt"`
	User      *models.User `json:"user"`
}

type LoginCredentialsInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PermissionMutationInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ProductMutationInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
}

type Query struct {
}

type RoleMutationInput struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	PermissionIds []uint `json:"permissionIds"`
}

type UserCreateInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	RoleID   uint   `json:"roleId"`
}

type UserUpdateInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password *string `json:"password,omitempty"`
	RoleID   uint    `json:"roleId"`
}
