package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/models"
	"backend/services"
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginCredentialsInput) (*model.AuthPayload, error) {
	user, err := r.UserService.Authenticate(mapLoginInput(input))
	if err != nil {
		if errors.Is(err, services.ErrInvalidCredentials) {
			return nil, services.ErrInvalidCredentials
		}

		return nil, err
	}

	token, expiresAt, err := r.JWTService.GenerateToken(user)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token:     token,
		ExpiresAt: expiresAt.Format(time.RFC3339),
		User:      &user,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserCreateInput) (*models.User, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_C_USUARIO"); err != nil {
		return nil, err
	}

	user, err := r.UserService.Create(mapCreateUserInput(input))
	if err != nil {
		return nil, err
	}

	return &user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uint, input model.UserUpdateInput) (*models.User, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_U_USUARIO"); err != nil {
		return nil, err
	}

	user, err := r.UserService.Update(id, mapUpdateUserInput(input))
	if err != nil {
		return nil, err
	}

	return &user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uint) (bool, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_D_USUARIO"); err != nil {
		return false, err
	}

	if err := r.UserService.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.RoleMutationInput) (*models.Role, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_C_ROL"); err != nil {
		return nil, err
	}

	role, err := r.RoleService.Create(mapRoleInput(input))
	if err != nil {
		return nil, err
	}

	return &role, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id uint, input model.RoleMutationInput) (*models.Role, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_U_ROL"); err != nil {
		return nil, err
	}

	role, err := r.RoleService.Update(id, mapRoleInput(input))
	if err != nil {
		return nil, err
	}

	return &role, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id uint) (bool, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_D_ROL"); err != nil {
		return false, err
	}

	if err := r.RoleService.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// CreatePermission is the resolver for the createPermission field.
func (r *mutationResolver) CreatePermission(ctx context.Context, input model.PermissionMutationInput) (*models.Permission, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_C_PERMISO"); err != nil {
		return nil, err
	}

	permission, err := r.PermissionService.Create(mapPermissionInput(input))
	if err != nil {
		return nil, err
	}

	return &permission, nil
}

// UpdatePermission is the resolver for the updatePermission field.
func (r *mutationResolver) UpdatePermission(ctx context.Context, id uint, input model.PermissionMutationInput) (*models.Permission, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_U_PERMISO"); err != nil {
		return nil, err
	}

	permission, err := r.PermissionService.Update(id, mapPermissionInput(input))
	if err != nil {
		return nil, err
	}

	return &permission, nil
}

// DeletePermission is the resolver for the deletePermission field.
func (r *mutationResolver) DeletePermission(ctx context.Context, id uint) (bool, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_D_PERMISO"); err != nil {
		return false, err
	}

	if err := r.PermissionService.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.ProductMutationInput) (*models.Product, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_C_PRODUCTO", "VEN_C_PRODUCTO"); err != nil {
		return nil, err
	}

	product, err := r.ProductService.Create(mapProductInput(input))
	if err != nil {
		return nil, err
	}

	return &product, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uint, input model.ProductMutationInput) (*models.Product, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_U_PRODUCTO", "VEN_U_PRODUCTO"); err != nil {
		return nil, err
	}

	product, err := r.ProductService.Update(id, mapProductInput(input))
	if err != nil {
		return nil, err
	}

	return &product, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uint) (bool, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_D_PRODUCTO"); err != nil {
		return false, err
	}

	if err := r.ProductService.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_USUARIO"); err != nil {
		return nil, err
	}

	users, err := r.UserService.FindAll()
	if err != nil {
		return nil, err
	}

	return toPointers(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uint) (*models.User, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_USUARIO"); err != nil {
		return nil, err
	}

	user, err := r.UserService.FindByID(id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}

		return nil, err
	}

	return &user, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*models.Role, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_ROL"); err != nil {
		return nil, err
	}

	roles, err := r.RoleService.FindAll()
	if err != nil {
		return nil, err
	}

	return toPointers(roles), nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id uint) (*models.Role, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_ROL"); err != nil {
		return nil, err
	}

	role, err := r.RoleService.FindByID(id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}

		return nil, err
	}

	return &role, nil
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context) ([]*models.Permission, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_PERMISO"); err != nil {
		return nil, err
	}

	permissions, err := r.PermissionService.FindAll()
	if err != nil {
		return nil, err
	}

	return toPointers(permissions), nil
}

// Permission is the resolver for the permission field.
func (r *queryResolver) Permission(ctx context.Context, id uint) (*models.Permission, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_PERMISO"); err != nil {
		return nil, err
	}

	permission, err := r.PermissionService.FindByID(id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}

		return nil, err
	}

	return &permission, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	user, err := CurrentUser(ctx)
	if err != nil {
		return nil, err
	}

	return &user, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*models.Product, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_PRODUCTO", "VEN_R_PRODUCTO"); err != nil {
		return nil, err
	}

	products, err := r.ProductService.FindAll()
	if err != nil {
		return nil, err
	}

	return toPointers(products), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id uint) (*models.Product, error) {
	if _, err := RequireAnyPermission(ctx, "ADM_R_PRODUCTO", "VEN_R_PRODUCTO"); err != nil {
		return nil, err
	}

	product, err := r.ProductService.FindByID(id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}

		return nil, err
	}

	return &product, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
